FROM postgres:17.4-alpine3.21

# Set environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=matbloom

# Expose the PostgreSQL port
EXPOSE 5432

# Use the default entrypoint provided by the postgres image